### ISSUE TITLE
First commit + push

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [DukeStatSci/thesis-sp18-wu-anomalydet#1]
When you receive the invite to the repo, please complete the following as soon as possible:

- [x] Make your first commit and push of the thesis template
- [x] Update your README to say a sentence about your project

Once you're done, you can comment here saying so, and close the issue.

**Comment by mine-cetinkaya-rundel** [comment]
@jamescwu It looks like these items are still pending. Could you update your README to say a paragraph about your project and also push your entire document (the gitbook) even if it has real content in only some of the sections? When done, please check off and close the issue.

**Comment by ghost** [comment]
updated readme and added the gitbook (in index file)
